---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: remediations
  name: remediations-consumer
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    app: remediations
    deploymentconfig: remediations-consumer
  strategy:
    type: Recreate
    activeDeadlineSeconds: 21600
  template:
    metadata:
      labels:
        app: remediations
        deploymentconfig: remediations-consumer
    spec:
      containers:
      - image: {{ .Values.imageRegistry }}/{{ .Values.imageNamespace }}/remediations-consumer:{{ .Values.istag | default "latest" }}
        imagePullPolicy: Always
        name: remediations-consumer
        env:
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: KAFKA_HOST
          value: {{ .Values.kafkaHost }}

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - remediations-consumer
      from:
        kind: ImageStreamTag
        name: remediations-consumer:{{ .Values.istag | default "latest" }}
        namespace: {{ .Values.imageNamespace }}
