version: 2
updates:
  # Check for latest Dockerfile parent image
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Check for updates to NPM packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
