version: 2
updates:
  # Check for latest Dockerfile parent image
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"

  # Check for updates to NPM packages
  - package-ecosystem: "npm"
    target-branch: "package_updates"
    directory: "/"
    schedule:
      interval: "weekly"
