#!/usr/bin/env groovy

@Library("github.com/RedHatInsights/insights-pipeline-lib@v3")

NS='remediations-pr'

def notify(subject, body, color) {
    message = subject
    if (body != null) {
        message += " | ${body}"
    }

    slackSend message: message, color: color, channel: '#remediations'
}

def notifyOnFailure(Closure step) {
    try {
        step()
    } catch (e) {
        notify("@jharting [${env.JOB_NAME.split('/')[-1]}] Build failed", "See ${env.BUILD_URL}console", "danger")
        throw e
    }
}

node('nodejs') {
    notifyOnFailure {
        notify("[${env.JOB_NAME.split('/')[-1]}] Build started", null, "#439FE0")

        env.NODEJS_HOME = "${tool 'node-10'}"
        env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"

        checkout scm

        def utils = load "./build/utils.groovy"

        sh 'git rev-parse HEAD'

        stage('build') {
            sh 'npm ci'
            sh 'npm run compile'
        }

        openshift.withCluster() {

            utils.withScaledEnv(NS) {
                env.DB_HOST="postgres.${NS}.svc"

                stage('verify') {
                    sh 'npm run verify'
                }
            }

            stage('build image') {
                timeout (10) {
                    openshift.withProject('buildfactory') {
                        def build = openshift.selector('bc', 'remediations-consumer').startBuild()
                        build.logs('-f')
                    }
                }
            }

            notify("[${env.JOB_NAME.split('/')[-1]}] Build finished", null, "good")
        }
    }
}
