---
apiVersion: v1
kind: Template
metadata:
  name: remediations-consumer
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: remediations-consumer
  spec:
    envName: ${ENV_NAME}
    database:
      sharedDbAppName: remediations
    dependencies:
    - remediations
    kafkaTopics:
    - replicas: 64
      partitions: 64
      topicName: platform.inventory.events
    deployments:
    - name: remediations-consumer
      minReplicas: ${{NUM_REPLICAS}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
          - name: DB_DRY_RUN
            value: ${DRY_RUN}
          - name: DB_SSL_ENABLED
            value: ${DB_SSL_ENABLED}
          - name: INVENTORY_RESET_OFFSETS
            value: ${INVENTORY_RESET_OFFSETS}
          - name: KAFKA_CONCURRENCY
            value: ${KAFKA_CONCURRENCY}
          - name: KAFKA_CONSUMER_GROUP
            value: ${KAFKA_CONSUMER_GROUP}
          - name: KAFKA_LOGGING
            value: ${KAFKA_LOGGING}
          - name: KAFKA_AUTOCOMMIT
            value: ${KAFKA_AUTOCOMMIT}
          - name: KAFKA_CONNECTION_TIMEOUT
            value: ${KAFKA_CONNECTION_TIMEOUT}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: LOG_CW_LEVEL
            value: ${LOG_LEVEL}
          - name: ADVISOR_TOPIC_ENABLED
            value: ${ADVISOR_TOPIC_ENABLED}
          - name: COMPLIANCE_TOPIC_ENABLED
            value: ${COMPLIANCE_TOPIC_ENABLED}
          - name: INVENTORY_TOPIC_ENABLED
            value: ${INVENTORY_TOPIC_ENABLED}
          - name: PATCH_TOPIC_ENABLED
            value: ${PATCH_TOPIC_ENABLED}
          - name: RECEPTOR_TOPIC_ENABLED
            value: ${RECEPTOR_TOPIC_ENABLED}
          - name: VULNERABILITY_TOPIC_ENABLED
            value: ${VULNERABILITY_TOPIC_ENABLED}
    jobs:
    - name: cleaner
      schedule: '@hourly'
      suspend: ${{CLEANER_SUSPEND}}
      podSpec:
        image: quay.io/cloudservices/remediations-consumer:${IMAGE_TAG}
        restartPolicy: Never
        command:
          - node
          - dist/src/cleaner/run.js
        env:
          - name: DB_SSL_ENABLED
            value: ${DB_SSL_ENABLED}
          - name: LOG_CW_LEVEL
            value: ${LOG_LEVEL}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: METRICS_PREFIX
            value: remediations_cleaner_
          - name: METRICS_PUSH_GATEWAY
            value: http://${PROMETHEUS_PUSHGATEWAY}
          - name: METRICS_PUSH_GATEWAY_ENABLED
            value: ${METRICS_PUSH_GATEWAY_ENABLED}
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 200m
            memory: 256Mi
parameters:
- name: DRY_RUN
  value: 'false'
- name: ENV_NAME
- name: LOG_LEVEL
  value: trace
- name: KAFKA_CONCURRENCY
  value: '1'
- name: KAFKA_CONSUMER_GROUP
  value: remediations-consumer
- name: INVENTORY_RESET_OFFSETS
  value: 'false'
- name: KAFKA_LOGGING
  value: 'false'
- name: KAFKA_AUTOCOMMIT
  value: 'true'
- name: KAFKA_CONNECTION_TIMEOUT
- name: NUM_REPLICAS
  value: '3'
- name: DB_SSL_ENABLED
  value: 'true'
- name: ADVISOR_TOPIC_ENABLED
  value: 'false'
- name: COMPLIANCE_TOPIC_ENABLED
  value: 'false'
- name: INVENTORY_TOPIC_ENABLED
  value: 'true'
- name: PATCH_TOPIC_ENABLED
  value: 'false'
- name: RECEPTOR_TOPIC_ENABLED
  value: 'true'
- name: VULNERABILITY_TOPIC_ENABLED
  value: 'false'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image
  name: IMAGE
  required: true
  value: "quay.io/redhat-services-prod/insights-management-tenant/insights-remediations/remediations-consumer"
- name: PROMETHEUS_PUSHGATEWAY
- name: METRICS_PUSH_GATEWAY_ENABLED
  value: 'true'
- description: Cpu limit of cleaner job
  name: CPU_LIMIT
  value: 200m
- description: memory limit of cleaner job
  name: MEMORY_LIMIT
  value: 256Mi
- name: CLEANER_SUSPEND
  value: 'true'
