---
apiVersion: v1
kind: Template
metadata:
  name: remediations-consumer
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: remediations-consumer
  spec:
    envName: ${ENV_NAME}
    database:
      sharedDbAppName: remediations
    kafkaTopics: 
    - replicas: 64
      partitions: 64
      topicName: platform.inventory.events
    - replicas: 3
      partitions: 3
      topicName: platform.receptor-controller.responses
    deployments:
    - name: remediations-consumer
      minReplicas: ${NUM_REPLICAS}
      podSpec:
        image: quay.io/cloudservices/remediations-consumer:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9006
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9006
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
          - name: DB_DRY_RUN
            value: ${DRY_RUN}
          - name: DB_CA
            value: /opt/certs/rds-cacert
          - name: DB_SSL_ENABLED
            value: ${DB_SSL_ENABLED}
          - name: INVENTORY_RESET_OFFSETS
            value: ${INVENTORY_RESET_OFFSETS}
          - name: KAFKA_CONCURRENCY
            value: ${KAFKA_CONCURRENCY}
          - name: KAFKA_CONSUMER_GROUP
            value: ${KAFKA_CONSUMER_GROUP}
          - name: KAFKA_HOST
            value: ${KAFKA_BOOTSTRAP_HOST}:${KAFKA_BOOTSTRAP_PORT}
          - name: KAFKA_LOGGING
            value: ${KAFKA_LOGGING}
          - name: KAFKA_AUTOCOMMIT
            value: ${KAFKA_AUTOCOMMIT}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: LOG_CW_ENABLED
            value: ${LOG_CW_ENABLED}
          - name: LOG_CW_LEVEL
            value: ${LOG_LEVEL}
          - name: ADVISOR_TOPIC_ENABLED
            value: ${ADVISOR_TOPIC_ENABLED}
          - name: COMPLIANCE_TOPIC_ENABLED
            value: ${COMPLIANCE_TOPIC_ENABLED}
          - name: INVENTORY_TOPIC_ENABLED
            value: ${INVENTORY_TOPIC_ENABLED}
          - name: PATCH_TOPIC_ENABLED
            value: ${PATCH_TOPIC_ENABLED}
          - name: RECEPTOR_TOPIC_ENABLED
            value: ${RECEPTOR_TOPIC_ENABLED}
          - name: VULNERABILITY_TOPIC_ENABLED
            value: ${VULNERABILITY_TOPIC_ENABLED}

parameters:
- name: DRY_RUN
  value: 'false'
- name: ENV_NAME
- name: LOG_LEVEL
  value: trace
- name: KAFKA_CONCURRENCY
  value: '1'
- name: KAFKA_CONSUMER_GROUP
  value: remediations-consumer
- name: INVENTORY_RESET_OFFSETS
  value: 'false'
- name: KAFKA_BOOTSTRAP_HOST
  value: mq-kafka
- name: KAFKA_BOOTSTRAP_PORT
  value: '29092'
- name: KAFKA_LOGGING
  value: 'false'
- name: KAFKA_AUTOCOMMIT
  value: 'true'
- name: NUM_REPLICAS
  value: '1'
- name: DB_SSL_ENABLED
  value: 'true'
- name: LOG_CW_ENABLED
  value: 'true'
- name: ADVISOR_TOPIC_ENABLED
  value: 'false'
- name: COMPLIANCE_TOPIC_ENABLED
  value: 'false'
- name: INVENTORY_TOPIC_ENABLED
  value: 'true'
- name: PATCH_TOPIC_ENABLED
  value: 'false'
- name: RECEPTOR_TOPIC_ENABLED
  value: 'true'
- name: VULNERABILITY_TOPIC_ENABLED
  value: 'false'
- description: Image tag
  name: IMAGE_TAG
  required: true
