imageRegistry: docker-registry.default.svc:5000
imageNamespace: buildfactory

logLevel: trace
replicas: 2

kafka:
  host: platform-mq-ci-kafka-bootstrap.platform-mq-ci.svc:9092
  logging: true

db: {}
